//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBiblioteca.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejemplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejemplar()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int IdEjemplar { get; set; }
        public Nullable<int> IdLibro { get; set; }
        public string Ubicacion { get; set; }
        public string Editorial { get; set; }
        public string Idioma { get; set; }
        public string Pais { get; set; }
        public string Estado { get; set; }
    
        public virtual Libro Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}
