//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBiblioteca.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int IdPrestamo { get; set; }
        public int IdEjemplar { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Ejemplar Ejemplar { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
